services:

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z 
    container_name: minio
    environment:
      - MINIO_ROOT_USER=User
      - MINIO_ROOT_PASSWORD=p4ssw0rd
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
