version: '3.9'

services:

  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z 
    container_name: minio
    environment:
      - MINIO_ROOT_USER=User
      - MINIO_ROOT_PASSWORD=p4ssw0rd
#      - MINIO_BROWSER_REDIRECT_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
#      - MINIO_DOMAIN=Host(`${APP_DOMAIN}`)
    ports:
      - "8000:9000"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - ./minio_data:/data
    command: "server --console-address :9001 /data"
